#!/usr/bin/perl -w

if($ARGV[0] ne "-l"){
	$regexp = shift(@ARGV);

	@lis = @ARGV;
	@files={};

	foreach $fi(@lis){
		open(FII,  "/usr/bin/find $fi  -print |") or die "Could not open file: dead";
		@tem=<FII>;
		push(@files,@tem);
	}

	chop @files;
	foreach $ll(@files){

		if(-f $ll && -T $ll){
			open (IN,"$ll")or die "Could not open file: dead";
			@line =<IN>;
			foreach $line(@line){
				if($line =~/$regexp/){print "$ll:$line"};
			}
		} 


		if(-f $ll && !-T $ll){
			open (IN1,"strings $ll|")or die "Could not open file: dead";
			@line1 =<IN1>;
			foreach $line1(@line1){
				if($line1 =~/$regexp/){print "$ll:$line1"};
			}
		}

	}
}


if($ARGV[0] eq "-l"){

	shift(@ARGV);
	$regexp = shift(@ARGV);

	@lis=@ARGV;
	@files={};

	foreach $fi(@lis){
		open(FII,  "/usr/bin/find $fi  -print |") or die "Could not open file: dead";
		@tem=<FII>;
		push(@files,@tem);
	}



	chop @files;
	foreach $ll(@files){

		if(-f $ll && -T $ll){
			open (IN,"$ll")or die "Could not open file: dead";
			@line =<IN>;
 
			@tt = grep(/$regexp/,@line);
			if (@tt!=0){print "$ll\n"};
		}

		if(-f $ll && ! -T $ll){
			open (INN,"strings $ll|")or die "Could not open file: dead";
			@line1 =<INN>;
  
			@tt1 = grep(/$regexp/,@line1);
			if(@tt1!=0){print "$ll\n"};
		}
	}
}
