#!/usr/bin/perl -w

while($file = <ARGV>){

#	sort $file;
	@line = sort(split(/:/, $file));
#	@sline = sort @line;
	print "$line[0]\t\t$line[4]\n";
#	print $sline[0], "\n";
#	print @sline, "\n";
}

#@line = sort(@line);

#foreach (@line){

#	print "$line[0]\t\t$line[4]\n";

#}

#@sline = sort @line;

#while(@sline !=0){
#	print "$sline[0]\n";
#}
