name myexp
comment This experiment contains 6 runs and tests context switch time.
run myrun algorithm PSJF key "PSJF"
comment run myrun algorithm SJF key "SJF"
comment run myrun algorithm PSJF key "PSJF cstin .5" cstin .5
comment run myrun algorithm SJF key "SJF cstin .5" cstin .5
comment run myrun algorithm PSJF key "PSJF cstin 1.0" cstin 1.0
comment run myrun algorithm SJF key "SJF cstin 1.0" cstin 1.0

