#!/usr/bin/perl -w

@all = `find @ARGV -print`;
chop @all;
#@dirs = grep (-d, @all);
@files = grep (-e, @all);
#@dirs = sort @dirs;
#print join ("\n", @dirs), "\n";
@files = sort @files;

$i = 1;

while ($i <= $#files){
	print join ("\n", $files[$i]), "\n";

	$i++;
}

#Maynard's Solution
#$dir = $ARGV[0];
#open(DIR,"/bin/ls $dir |") || die "Unable to open directory $ARGV[0]: $!\n";
#while ( <DIR> ) {
#  print "$dir/$_";
#}

