#!/usr/bin/perl -w

$fileout = pop;
$file1 = shift;
$file2 = shift;

open(OUT, "> $fileout") or die;
open(IN1, $file1) or die;
open(IN2, $file2) or die;

$a = <IN1>;
$b = <IN2>;

while ($a  || $b ){
	print OUT $a;
	print OUT $b;
	$a = <IN1>;
	$b = <IN2>;
}
