#!/usr/bin/perl -w

$regexp = "$ARGV[0] $ARGV[1]";

#print "$regexp\n";

$fin = open(IN, "./tc");

while(<IN>){
	if(/$regexp/){
		if(/hishaam\.1\.1\:00/ || /129\.115\.255\.255\:111/){
			print $_;
		}
	}


}
